// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFKHndJOJtsxhuOfYgI4HuTB2fDcaNF6U',
    appId: '1:80507381205:web:be84f898be8a5a9df0495c',
    messagingSenderId: '80507381205',
    projectId: 'luna-cool-project',
    authDomain: 'luna-cool-project.firebaseapp.com',
    storageBucket: 'luna-cool-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4F1PmHFsi-SASfluxl95FgttPnilRN0M',
    appId: '1:80507381205:android:c39e99eabe408fa5f0495c',
    messagingSenderId: '80507381205',
    projectId: 'luna-cool-project',
    storageBucket: 'luna-cool-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEj-RjmTftkmdQSvzk0tf3mzlLqTGoiMQ',
    appId: '1:80507381205:ios:996372cdc228dfbff0495c',
    messagingSenderId: '80507381205',
    projectId: 'luna-cool-project',
    storageBucket: 'luna-cool-project.firebasestorage.app',
    androidClientId: '80507381205-05nu5r9s2dbh3f8rtg60smfk4p79kii1.apps.googleusercontent.com',
    iosClientId: '80507381205-1ed2vnvq48vk6af6lsf5f5bp2kku3sur.apps.googleusercontent.com',
    iosBundleId: 'com.examplee.luna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEj-RjmTftkmdQSvzk0tf3mzlLqTGoiMQ',
    appId: '1:80507381205:ios:996372cdc228dfbff0495c',
    messagingSenderId: '80507381205',
    projectId: 'luna-cool-project',
    storageBucket: 'luna-cool-project.firebasestorage.app',
    androidClientId: '80507381205-05nu5r9s2dbh3f8rtg60smfk4p79kii1.apps.googleusercontent.com',
    iosClientId: '80507381205-1ed2vnvq48vk6af6lsf5f5bp2kku3sur.apps.googleusercontent.com',
    iosBundleId: 'com.examplee.luna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFKHndJOJtsxhuOfYgI4HuTB2fDcaNF6U',
    appId: '1:80507381205:web:d5ea3569396dbdc1f0495c',
    messagingSenderId: '80507381205',
    projectId: 'luna-cool-project',
    authDomain: 'luna-cool-project.firebaseapp.com',
    storageBucket: 'luna-cool-project.firebasestorage.app',
  );
}
